# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"set_seed": "00_core.ipynb",
         "bstack": "00_core.ipynb",
         "to_one_hot": "00_core.ipynb",
         "reformat_batch": "00_core.ipynb",
         "DenseRepresentation": "00_core.ipynb",
         "DenseDynamic": "00_core.ipynb",
         "DensePrediction": "00_core.ipynb",
         "MuModel": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://svenssona.github.io/muzero/"

git_url = "https://github.com/svenssona/muzero/tree/master/"

def custom_doc_links(name): return None
